### ISSUE TITLE
The type or namespace name 'Codice' could not be found 

### ISSUE THREAD

**Issue by TaylaWilson** [edgegap/edgegap-unity-plugin#26]
I have just freshly installed the plugin using the Git URL and Unity Package Manager and upon the project building I get the following:

Library\PackageCache\com.edgegap.unity-servers-plugin\Editor\EdgegapWindowV2.cs(11,7): error CS0246: The type or namespace name 'Codice' could not be found (are you missing a using directive or an assembly reference?)

Unity version: Unity 6 (6000.0.29f1)
EdgeGap plugin version: 3.0.7

**Comment by orcist** [comment]
resolved by #27 , updating your plugin through Unity Package Manager should fix the issue
